### ISSUE TITLE
Unable to reproduce dataset using the Ruby Script

### ISSUE THREAD

**Issue by asrjy** [LBNL-ETA/AlphaBuilding-SyntheticDataset#1]
I have installed both OpenStudio 2.9.1 and Ruby 2.2.4 installed. When I try to run the simulation for a single city, the script runs for about two minutes and ends. Then when I use the Python Script to extract the results into a CSV format, nothing is being generated. 

The following is what I get in the command prompt when I run it. 
https://pastebin.com/LBj99MMG

This is what I get when I try to extract the results using Python Script.
https://pastebin.com/Rd087aPj

No CSV file is being created.

**Comment by asrjy** [comment]
I'm also getting the following error when trying to simulate. 

[18:47:32.482359 ERROR] Found error in state 'initialization' with message ["Cannot find measure Occupancy_Simulator_Office::/ruby/2.2.0/gems/openstudio-workflow-1.3.4/lib/openstudio/workflow/util/measure.rb:150:in `block in validate_measures'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.4/lib/openstudio/workflow/util/measure.rb:136:in `each'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.4/lib/openstudio/workflow/util/measure.rb:136:in `each_with_index'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.4/lib/openstudio/workflow/util/measure.rb:136:in `validate_measures'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.4/lib/openstudio/workflow/jobs/run_initialization.rb:119:in `perform'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.4/lib/openstudio/workflow/run.rb:285:in `step'\n:/ruby/2.2.0/gems/openstudio-workflow-1.3.4/lib/openstudio/workflow/run.rb:232:in `run'\n:/openstudio_cli.rb:975:in `execute'\n:/openstudio_cli.rb:763:in `execute'\n:/openstudio_cli.rb:1746:in `<main>'\neval:116:in `eval'\neval:116:in `require_embedded_absolute'\neval:101:in `block in require'\neval:95:in `each'\neval:95:in `require'\neval:3:in `<main>'"]}

**Comment by tsbyq** [comment]
1. Make sure the `measures_dir` is set correctly so that OpenStudio can find the measures during simulation.
2. The available output variable and meters may differ among the selected building types. Please check if they are available before running.
