### ISSUE TITLE
Error in state initialization with message "Cannot find measure Occupancy Simulator Office"

### ISSUE THREAD

**Issue by asrjy** [LBNL-ETA/AlphaBuilding-SyntheticDataset#2]
[10:44:27.541894 ERROR] Found error in state 'initialization' with message "Cannot find measure Occupancy_Simulator_Office::/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:155:in `block in validate_measures':/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:141:in `each':/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:141:in `each_with_index':/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/util/measure.rb:141:in `validate_measures':/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/jobs/run_initialization.rb:122:in `perform':/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:291:in `step':/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:233:in `run':/openstudio_cli.rb:1067:in `execute':/openstudio_cli.rb:803:in `execute':/openstudio_cli.rb:1855:in `<main>'eval:186:in `eval'eval:186:in `require_embedded_absolute'eval:171:in `block in require_embedded'eval:165:in `each'eval:165:in `require_embedded'eval:124:in `require'eval:3:in `<main>'"

Getting the above error when trying to simulate the dataset for Texas EPW file.

**Comment by asrjy** [comment]
Hello. Any idea how to fix this issue?
